2025-09-30 14:03:52,213 - src.infrastructure.services.logger - INFO - Бот запущен
2025-09-30 14:03:52,476 - aiogram.dispatcher - INFO - Start polling
2025-09-30 14:03:52,697 - aiogram.dispatcher - INFO - Run polling for bot @heavenyoung_testbot id=5702092394 - 'testtest'
2025-09-30 14:04:01,296 - src.core.db_connection - INFO - Инициализация подключения к БД: postgresql+psycopg2://postgres:1234@10.165.1.93:5432/pricely_db
2025-09-30 14:04:01,642 - src.core.uow - INFO - Unit of Work инициализирован с сессией и репозиториями
2025-09-30 14:04:02,446 - src.infrastructure.database.repositories.user_repository - INFO - Пользователь User(id='515084006', username='heavenyoung', chat_id='515084006', products=['2000108942', '1818184981', '1728110604']) получен по id: 515084006
2025-09-30 14:04:02,446 - src.application.use_cases.create_user - INFO - Пользователь 515084006 уже существует, пропускаем создание
2025-09-30 14:04:02,447 - src.core.decorators - INFO - Функция create_user: выполняется commit транзакции
2025-09-30 14:04:02,453 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:04:02,454 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:04:02,455 - src.core.uow - INFO - Unit of Work завершил работу, сессия закрыта
2025-09-30 14:04:02,456 - src.infrastructure.services.logger - INFO - Пользователь 515084006 создан или уже существует
2025-09-30 14:04:02,482 - src.infrastructure.services.logger - WARNING - Ошибка создания пользователя 515084006: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={'resize_keyboard': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-09-30 14:04:02,502 - aiogram.event - INFO - Update id=557184935 is not handled. Duration 1207 ms by bot id=5702092394
2025-09-30 14:04:02,503 - aiogram.event - ERROR - Cause exception while process update id=557184935 by bot id=5702092394
UnboundLocalError: cannot access local variable 'keyboard' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\src\presentation\bot\handlers\start.py", line 23, in command_start_handler
    reply_markup=keyboard
                 ^^^^^^^^
UnboundLocalError: cannot access local variable 'keyboard' where it is not associated with a value
2025-09-30 14:05:05,198 - aiogram.dispatcher - INFO - Polling stopped
2025-09-30 14:05:05,202 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2025-09-30 14:05:05,202 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5702092394)
2025-09-30 14:05:05,368 - aiogram.dispatcher - INFO - Polling stopped for bot @heavenyoung_testbot id=5702092394 - 'testtest'
2025-09-30 14:05:11,335 - src.infrastructure.services.logger - INFO - Бот запущен
2025-09-30 14:05:11,742 - aiogram.dispatcher - INFO - Start polling
2025-09-30 14:05:11,978 - aiogram.dispatcher - INFO - Run polling for bot @heavenyoung_testbot id=5702092394 - 'testtest'
2025-09-30 14:05:15,001 - src.core.db_connection - INFO - Инициализация подключения к БД: postgresql+psycopg2://postgres:1234@10.165.1.93:5432/pricely_db
2025-09-30 14:05:15,104 - src.core.uow - INFO - Unit of Work инициализирован с сессией и репозиториями
2025-09-30 14:05:15,230 - src.infrastructure.database.repositories.user_repository - INFO - Пользователь User(id='515084006', username='heavenyoung', chat_id='515084006', products=['2000108942', '1818184981', '1728110604']) получен по id: 515084006
2025-09-30 14:05:15,230 - src.application.use_cases.create_user - INFO - Пользователь 515084006 уже существует, пропускаем создание
2025-09-30 14:05:15,230 - src.core.decorators - INFO - Функция create_user: выполняется commit транзакции
2025-09-30 14:05:15,233 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:05:15,234 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:05:15,234 - src.core.uow - INFO - Unit of Work завершил работу, сессия закрыта
2025-09-30 14:05:15,235 - src.infrastructure.services.logger - INFO - Пользователь 515084006 создан или уже существует
2025-09-30 14:05:15,235 - aiogram.event - INFO - Update id=557184936 is not handled. Duration 234 ms by bot id=5702092394
2025-09-30 14:05:15,236 - aiogram.event - ERROR - Cause exception while process update id=557184936 by bot id=5702092394
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={'resize_keyboard': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\src\presentation\bot\handlers\start.py", line 21, in command_start_handler
    keyboard = main_manu()
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\src\presentation\bot\keyboard\main_menu.py", line 8, in main_manu
    kb = ReplyKeyboardMarkup(resize_keyboard=True)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={'resize_keyboard': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-09-30 14:06:12,561 - aiogram.dispatcher - INFO - Polling stopped
2025-09-30 14:06:12,563 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2025-09-30 14:06:12,563 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5702092394)
2025-09-30 14:06:12,736 - aiogram.dispatcher - INFO - Polling stopped for bot @heavenyoung_testbot id=5702092394 - 'testtest'
2025-09-30 14:06:17,719 - src.infrastructure.services.logger - INFO - Бот запущен
2025-09-30 14:06:18,068 - aiogram.dispatcher - INFO - Start polling
2025-09-30 14:06:18,248 - aiogram.dispatcher - INFO - Run polling for bot @heavenyoung_testbot id=5702092394 - 'testtest'
2025-09-30 14:06:20,512 - src.core.db_connection - INFO - Инициализация подключения к БД: postgresql+psycopg2://postgres:1234@10.165.1.93:5432/pricely_db
2025-09-30 14:06:20,598 - src.core.uow - INFO - Unit of Work инициализирован с сессией и репозиториями
2025-09-30 14:06:20,788 - src.infrastructure.database.repositories.user_repository - INFO - Пользователь User(id='515084006', username='heavenyoung', chat_id='515084006', products=['2000108942', '1818184981', '1728110604']) получен по id: 515084006
2025-09-30 14:06:20,789 - src.application.use_cases.create_user - INFO - Пользователь 515084006 уже существует, пропускаем создание
2025-09-30 14:06:20,789 - src.core.decorators - INFO - Функция create_user: выполняется commit транзакции
2025-09-30 14:06:20,791 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:06:20,793 - src.core.uow - INFO - Unit of Work: транзакция зафиксирована, commit выполнен
2025-09-30 14:06:20,794 - src.core.uow - INFO - Unit of Work завершил работу, сессия закрыта
2025-09-30 14:06:20,794 - src.infrastructure.services.logger - INFO - Пользователь 515084006 создан или уже существует
2025-09-30 14:06:20,795 - aiogram.event - INFO - Update id=557184937 is not handled. Duration 283 ms by bot id=5702092394
2025-09-30 14:06:20,796 - aiogram.event - ERROR - Cause exception while process update id=557184937 by bot id=5702092394
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={'resize_keyboard': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\src\presentation\bot\handlers\start.py", line 21, in command_start_handler
    keyboard = main_menu()
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\src\presentation\bot\keyboard\main_menu.py", line 8, in main_menu
    kb = ReplyKeyboardMarkup(resize_keyboard=True)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={'resize_keyboard': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-09-30 14:09:01,569 - aiogram.dispatcher - INFO - Polling stopped
2025-09-30 14:09:01,572 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2025-09-30 14:09:01,572 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5702092394)
2025-09-30 14:09:01,732 - aiogram.dispatcher - INFO - Polling stopped for bot @heavenyoung_testbot id=5702092394 - 'testtest'
