2025-09-18 16:41:21,434 - __main__ - INFO - Запуск Telegram-бота
2025-09-18 16:41:22,812 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:22,814 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:26,166 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:26,168 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:26,762 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:26,764 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:30,860 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:30,865 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:32,962 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:32,964 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:37,081 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:37,083 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:45,178 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:45,180 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:41:56,570 - __main__ - INFO - Запуск Telegram-бота
2025-09-18 16:41:57,852 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:41:57,853 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:01,194 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:01,196 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:01,789 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:01,791 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:05,895 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:05,900 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:07,993 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:07,996 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:12,089 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:12,093 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:20,188 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:20,191 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:42:36,294 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:42:36,297 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:43:08,392 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:43:08,395 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:44:08,490 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:44:08,491 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:45:08,583 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:45:08,586 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:46:08,678 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:46:08,681 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:47:08,773 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:47:08,776 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:48:08,867 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:48:08,869 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:49:08,963 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:49:08,967 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:50:09,063 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:50:09,066 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:51:09,186 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:51:09,191 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:52:09,934 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:52:09,936 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:53:10,027 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:53:10,030 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:54:10,153 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:54:10,156 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:55:10,249 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:55:10,252 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-18 16:56:10,347 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-09-18 16:56:10,349 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Mefyod-EA\Documents\my_projects\pricely\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

2025-09-23 09:04:17,930 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:04:17,931 - src.infrastructure.parsers.session_decorator - ERROR - Ошибка в декорируемой функции: OzonParser.extract_name() takes 2 positional arguments but 3 were given
2025-09-23 09:04:20,310 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:17:01,532 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:17:03,841 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:18:48,778 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:18:48,779 - __main__ - INFO - ССЫЛКА: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:18:51,102 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:22:33,051 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:22:43,464 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:22:43,606 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:22:43,612 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:22:46,156 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:30:23,110 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:30:33,506 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:30:33,556 - __main__ - INFO - Найдено DEFAULT товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:30:33,557 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:30:36,016 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:31:30,747 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:31:41,095 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:31:41,140 - __main__ - INFO - Найдено DEFAULT товара: <selenium.webdriver.remote.webelement.WebElement (session="c90416a975c4b0c09df0260a23720cf6", element="f.E5B59E04CB9FD307C328C66CC8F83197.d.B135CFB83412C3C67F5EA30D8C44AED4.e.17")>
2025-09-23 09:31:41,141 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:31:43,631 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:49:52,365 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:50:02,732 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:50:02,787 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:50:05,346 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 09:57:24,944 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 09:57:35,371 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 09:57:35,429 - __main__ - INFO - Найдено название товара: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 09:57:37,939 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:43:05,473 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:43:15,879 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:43:15,938 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 12:43:18,407 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:45:14,539 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:45:24,979 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:45:25,037 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 12:45:27,532 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:45:28,719 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:45:39,045 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:45:39,083 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 12:45:41,596 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:48:25,958 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:48:36,403 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:48:36,446 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 12:48:38,961 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:48:40,169 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:48:50,496 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:48:50,833 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 12:48:53,518 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 12:48:54,846 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 12:49:12,369 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 12:49:12,486 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 12:49:14,916 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:18:09,554 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:18:19,991 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:18:20,065 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 13:18:22,835 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:18:24,148 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:18:34,482 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:18:35,290 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 13:18:38,247 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:18:39,485 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:18:50,151 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:18:50,224 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-23 13:18:54,500 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:47:42,300 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:47:52,727 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:47:52,784 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 13:47:55,273 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:47:56,523 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:48:06,866 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:48:06,935 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 13:48:09,484 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:48:10,680 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:48:21,016 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:48:21,630 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-23 13:48:24,337 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:48:25,526 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:48:35,847 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:48:35,909 - __main__ - INFO - Найдена информация о товаре: Артикул: 1723889987
2025-09-23 13:48:38,602 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:54:26,117 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:54:36,560 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:54:36,943 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 13:54:39,473 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:54:40,728 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:54:51,048 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:54:51,097 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 13:54:53,696 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:54:54,887 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:55:05,212 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:55:05,807 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-23 13:55:08,411 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:55:09,664 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:55:19,989 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:55:20,349 - __main__ - INFO - Найдена информация о товаре: Артикул: 1723889987
2025-09-23 13:55:24,654 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 13:55:25,893 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 13:55:36,267 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 13:55:36,368 - __main__ - INFO - Найдена информация о товаре: Обувь
2025-09-23 13:55:38,928 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:06:00,297 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:06:10,714 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:06:11,389 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 14:06:14,060 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:06:15,368 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:06:25,725 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:06:25,810 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 14:06:28,615 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:06:29,906 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:06:40,588 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:06:40,650 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-23 14:06:43,189 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:06:44,426 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:06:54,750 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:06:54,809 - __main__ - INFO - Найдена информация о товаре: Артикул: 1723889987
2025-09-23 14:06:57,373 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:06:58,558 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:07:08,874 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:07:08,942 - __main__ - INFO - Найдена информация о товаре: Обувь
2025-09-23 14:07:13,083 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:07:14,265 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:07:24,591 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:07:24,697 - __main__ - INFO - Найдена информация о товаре: 4.8 • 14 005 отзывов
2025-09-23 14:07:27,437 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:37:13,092 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:37:24,000 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:37:32,215 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-23 14:37:33,965 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:37:35,321 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:37:46,968 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:37:47,095 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-23 14:37:48,855 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:37:50,302 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:38:01,486 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:38:01,595 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-23 14:38:03,331 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:38:04,730 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:38:15,625 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:38:16,078 - __main__ - INFO - Найдена информация о товаре: Артикул: 1723889987
2025-09-23 14:38:17,900 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:38:19,296 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:38:30,250 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:38:30,311 - __main__ - INFO - Найдена информация о товаре: Обувь
2025-09-23 14:38:30,311 - __main__ - ERROR - Ошибка при извлечении названия товара: 'str' object has no attribute 'text'
2025-09-23 14:38:31,899 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-23 14:38:33,084 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-23 14:38:44,005 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-23 14:38:44,064 - __main__ - INFO - Найдена информация о товаре: 4.8 • 14 012 отзывов
2025-09-23 14:38:45,577 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:12:40,848 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:12:52,369 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:13:01,617 - __main__ - INFO - Найдена информация о товаре: Арома стикеры для обуви 30 шт. Дезодорант для обуви антибактериальный
2025-09-25 21:13:03,414 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:13:04,734 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:13:17,044 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:13:17,095 - __main__ - INFO - Найдена информация о товаре: 208 ₽
2025-09-25 21:13:18,722 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:13:19,944 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:13:31,726 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:13:31,818 - __main__ - INFO - Найдена информация о товаре: 228 ₽
2025-09-25 21:13:33,498 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:13:34,739 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:13:46,654 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:13:46,848 - __main__ - INFO - Найдена информация о товаре: Артикул: 1723889987
2025-09-25 21:13:48,908 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:13:50,902 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:14:03,397 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:14:03,530 - __main__ - INFO - Найдена информация о товаре: Обувь
2025-09-25 21:14:03,531 - __main__ - ERROR - Ошибка при извлечении названия товара: 'str' object has no attribute 'text'
2025-09-25 21:14:05,353 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:14:06,854 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:14:18,904 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:14:18,988 - __main__ - INFO - Найдена информация о товаре: 4.8 • 14 215 отзывов
2025-09-25 21:14:20,719 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:14:22,146 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:14:33,691 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:14:33,793 - __main__ - INFO - Найдена информация о товаре: 4.8 • 14 215 отзывов
2025-09-25 21:14:35,505 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:17:21,040 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:17:32,747 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:17:32,793 - __main__ - INFO - Найдена информация о товаре: https://ir.ozone.ru/s3/multimedia-1-1/wc50/7182410941.jpg
2025-09-25 21:17:34,525 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:18:07,407 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:18:18,883 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:18:18,942 - __main__ - INFO - Найдена информация о товаре: https://ir.ozone.ru/s3/multimedia-1-1/wc50/7182410941.jpg
2025-09-25 21:18:18,942 - __main__ - ERROR - Ошибка при извлечении названия товара: 'OzonParser' object has no attribute '_extract_text'
2025-09-25 21:18:20,564 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
2025-09-25 21:18:38,372 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно инициализирован.
2025-09-25 21:18:49,855 - src.infrastructure.parsers.session_engine - INFO - Успешно загружена страница: https://www.ozon.ru/product/aroma-stikery-dlya-obuvi-30-sht-dezodorant-dlya-obuvi-antibakterialnyy-1723889987/?at=DqtDqnm7Nup54QYmswEpQYXFpp2VXvSM0rqokI66QJ32
2025-09-25 21:18:49,904 - __main__ - INFO - Найдена информация о товаре: https://ir.ozone.ru/s3/multimedia-1-1/wc50/7182410941.jpg
2025-09-25 21:18:51,659 - src.infrastructure.parsers.session_engine - INFO - WebDriver успешно закрыт.
